piyushg-07/blogzen-OpenSource

chatBot/style.css

This PR fixes the position of "Chatbot" on Homepage.
Fixes#10

Fixed the Chatbot Position

---

css/navbar.css

#issue:37
I've adjusted the sign in page by positioning it properly in the centre of the page and also adding proper padding to give proper breathing space to it  and also added the hover effect which is more appealing and now it looks more engaging .

adjusted the signup page

---

css/navbar.css
index.html
js/theme.js

Please review the code changes for the addition of calendar and kindly approve. (Calendar pops up when clicked on Calendar button)

Added Calender

---

css/desktop_9.css
index.html
js/theme.js

Fixed #154 
Calendar is not looking properly in dark mode, solved this issue
* Click on calendar button
* Then click on dark mode button
https://github.com/piug-07/blogzen-OpenSource/assets/114382367/79d73c9c-30ea-4764-9134-15df6fc8f76f

Calendar bg

---

README.md
css/navbar.css
css/sec1.css
index.html
js/Landingpage.js

I made the change according to issue  [#6 ](url) @piug-07 please check

 Cursor as Pointer on hover in NavBar also Added Close button on the login/signup pop up

---

css/sec4.css
index.html
js/theme.js

solved issue #306 
I wrote a function to check  email pattern and display warning until user start editing the input to correct it.
https://github.com/piug-07/blogzen-OpenSource/assets/161131072/21448f87-8b6b-4e2a-a9e8-9d3e06702ba5
https://github.com/piug-07/blogzen-OpenSource/assets/161131072/4ed8ba82-cef6-4057-8b2f-6e4f7e903b5d

Added basic email validation to subscribe to newsletter 

---

CODE_OF_CONDUCT.md

created codeOfconduct.md

---

README.md
index.html

The alt tag are important for accessibility and is used within HTML to provide a text alternative to an image if the image cannot be displayed or if it is being accessed by someone using assistive technology like screen readers. This ensures that people with visual impairments can still understand the content of the image.

Added the alt tag in the social media icons at the footer of the website

---

css/sec3.css

Before
After
solved #246 
please check my PR @piug-07 
can you please add the labels for GSSOC @piug-07

Solved issue of overflowing

---

index.html

the spelling of calendar is corrected.
fixes #251 
before:
after:

fixed: spelling of calendar

---

js/theme.js

The navbar background color kept white while toggling dark mode which is fixed and also a different dark mode icon because the previous one would hide in the  black bgcolor.
Thank You!
Here's how it looks now:
fixes: #158

fixed navbar bgcolor to black in dark mode

---

database/jsonData.json
index.html
js/blog.js

Reverts piug-07/blogzen-OpenSource#157

Revert "Added Blogs"

---

css/sec3.css

Reverts piug-07/blogzen-OpenSource#312

Revert "Solved issue of overflowing"

---

css/desktop_9.css

Reverts piug-07/blogzen-OpenSource#181

Revert "Login bg"

---

css/navbar.css
css/sec1.css
index.html
js/Landingpage.js

Reverts piug-07/blogzen-OpenSource#9

Revert " Cursor as Pointer on hover in NavBar also Added Close button on the login/signup pop up"

---

css/sec4.css
index.html
js/theme.js

Reverts piug-07/blogzen-OpenSource#320

Revert "Added basic email validation to subscribe to newsletter "

---

README.md
index.html

Reverts piug-07/blogzen-OpenSource#100

Revert "Added the alt tag in the social media icons at the footer of the website"

---

database/jsonData.json

As mentioned in issue #314 , I have added a blog on Introduction to DevOps. Please let me know if any additional changes are required.

Added Blog on DevOps 

---

css/sec1.css
css/sec2.css

BUG: Added Hovering Effect to Buttons
This pull request addresses the issue #471 by adding a hover effect to buttons across the Blogzen-Opensource application. The changes enhance user experience by providing visual feedback when interacting with buttons.
- Added CSS rules to implement a hover effect for buttons.
- Ensured the hover effect is consistent across all buttons in the application.
- Verified that the hover effect does not interfere with existing animations or interactive elements.
The hover effect improves the clarity of interactive elements, aligning with modern UI/UX practices. It is designed to be subtle yet noticeable, adhering to accessibility guidelines to support users with visual impairments.
---
Thankyou for considering this PR! @piug-07

added hovering effect to buttons

---

index.html

#434 
The message gets popped up on successful subscription once an email address is entered, else the error message gets displayed.
Along with that if the email address is invalid the error message gets displayed.

Message added on successful subscription #434

---

js/blog.js

[Please link to any related issue(s) this pull request addresses. If none, simply state “None”]
[Please provide a brief overview of the changes or features added in this pull request.]
[Attach any relevant screenshots or videos demonstrating the changes made, if applicable.]
[Include any additional information or context that might be helpful for reviewers. This could include details about any design decisions, potential impacts, or alternative approaches considered.]

Add my new feature

---

js/blog.js

[Please link to any related issue(s) this pull request addresses. If none, simply state “None”]
[Please provide a brief overview of the changes or features added in this pull request.]
[Attach any relevant screenshots or videos demonstrating the changes made, if applicable.]
[Include any additional information or context that might be helpful for reviewers. This could include details about any design decisions, potential impacts, or alternative approaches considered.]

Add second feature

---

css/desktop_9.css
css/navbar.css

Footer fixed to Responsive in all devices
- [ x] I have performed a self-review of my code.
- [ x] I have read and followed the Contribution Guidelines outlined in the project's documentation.
- [ x] I have thoroughly tested the changes before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ x] I have commented my code, particularly in hard-to-understand areas.
[Include any additional information or context that might be helpful for reviewers. This could include details about any design decisions, potential impacts, or alternative approaches considered.]

Fixed the issue #496

---

css/sec2.css
css/sec3.css

fixes #538 
This PR basically add smoothness to Image Hover of sections.
https://github.com/piug-07/blogzen-OpenSource/assets/87531466/273540d2-841e-4b66-a8d4-779bb74da83e

fix: Fix Image hover smoothness

---

css/navbar.css

Improper Styling and Hovering of Buttons :
The LogIn and the Calender Buttons and not properly styled as the anchor tag is not provided with styling and the Calender button is larger than the rest 2 buttons 
The hovering effect isn't working as there is improper CSS styling to it

Proper Hovering Effect  and Styling of Navbar Buttons
